name: Build and deploy openchess-api to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-openchess-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push openchess-api image to GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/boehnen/openchess-api:${{ github.sha }}

  deploy-openchess-api:
    runs-on: ubuntu-latest
    needs: build-openchess-api
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy openchess-api to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openchess-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'ghcr.io/boehnen/openchess-api:${{ github.sha }}'
